'use strict';
const SETS=window.FLIGHT_SETS, ALL=SETS.flatMap(s=>s.words), BY_ID=new Map(ALL.map(w=>[w.id,w]));
const KEY='kotoba-flight-v1', LEVELS=['A1','A2','B1','B2'], PILOTS={wizard:['🧙','魔法使い'],bird:['🐦','鳥'],plane:['✈️','飛行機']};
const app=document.getElementById('app');
let memoryWarning=false, state, route={view:'home'}, game=null, raf=0, lastResult=null, toastTimer;
function fresh(){return {version:1,pilot:'wizard',audio:false,lastSet:null,words:{},best:0,flights:0};}
try{const x=JSON.parse(localStorage.getItem(KEY));state=x&&x.version===1&&x.words&&typeof x.words==='object'?{...fresh(),...x}:fresh();}catch{state=fresh();memoryWarning=true;}
if(!PILOTS[state.pilot])state.pilot='wizard';
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{memoryWarning=true;toast('このブラウザーでは記録を保存できません。');}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function status(id){const x=state.words[id];return x&&typeof x==='object'?x:{seen:0,correct:0,wrong:0,streak:0,review:false,lastSession:''};}
function counts(words){return {seen:words.filter(w=>status(w.id).seen>0).length,mastered:words.filter(w=>status(w.id).streak>=3).length,review:words.filter(w=>status(w.id).review).length};}
function currentSet(){return SETS.find(s=>s.id===state.lastSet)||SETS[0];}
function bySet(id){return SETS.find(s=>s.id===id)||SETS[0];}
function shuffle(xs){const a=[...xs];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.style.display='none',4500);}
function progress(n,d){return `<div class="progress" role="progressbar" aria-label="習得状況" aria-valuenow="${n}" aria-valuemin="0" aria-valuemax="${d}"><span style="width:${d?n/d*100:0}%"></span></div>`;}
function header(){return `<header><button class="brand" data-action="home">ことばフライト<small>VIETNAMESE VOCABULARY</small></button><span class="tag">ベトナム語 → 日本語</span></header>`;}
function footer(){return `<details class="footer-note"><summary>学習記録・単語レベルについて</summary><p>記録はこのブラウザーだけに保存されます。端末間の同期はなく、ブラウザーのデータを消すと記録も消えます。習得済みは、別々のゲームで3回連続正解した単語です。不正解で連続記録はリセットされます。</p><p>2,000語・表現の初期教材です。CEFRの能力記述と学習テーマを参考にした独自の暫定分類で、公式認定や各レベルの網羅を示すものではありません。日本語訳は出題する意味に絞っています。</p><p>参考：<a href="https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors-search" target="_blank" rel="noopener">CEFR</a><a href="https://openbooks.lib.msu.edu/vietnamese/" target="_blank" rel="noopener">Basic Vietnamese</a><a href="https://vietnamesenotes.app/en/vocabulary/b1" target="_blank" rel="noopener">学習テーマ</a><a href="https://github.com/katochoko/vietnamese-step" target="_blank" rel="noopener">Vietnamese Step</a></p></details>`;}
function crumbs(s,theme){return `<nav class="breadcrumbs" aria-label="現在の場所"><button data-action="home">ホーム</button><span>›</span><button data-action="level" data-id="${s.level}">${s.level}</button>${theme?`<span>›</span><button data-action="theme" data-level="${s.level}" data-id="${esc(s.theme)}">${esc(s.theme)}</button>`:''}</nav>`;}
function go(view,args={}){if(game&&!game.finished)return;route={view,...args};render();window.scrollTo(0,0);}
function render(){document.body.classList.toggle('game-page',route.view==='game');app.innerHTML=header()+(route.view==='home'?home():route.view==='level'?levelView():route.view==='theme'?themeView():route.view==='set'?setView():route.view==='review'?reviewView():route.view==='result'?resultView():gameView());if(memoryWarning&&route.view==='home')toast('記録の保存が利用できない可能性があります。');}
function home(){const s=currentSet(),c=counts(ALL),sc=counts(s.words);return `<main class="shell"><div class="welcome"><div class="eyebrow">YOUR LEARNING JOURNEY</div><h1>今日も、20語から飛び立とう。</h1><p class="muted">レベルとテーマを選んで、2分間の単語フライト。</p></div><div class="dashboard"><section class="card home-card"><div class="sky"><span class="sky-label">VIETNAM · WORD FLIGHT</span><span class="pilot idle" aria-hidden="true">${PILOTS[state.pilot][0]}</span><div class="sky-caption"><div>${state.lastSet?'あなたの次のフライト':'はじめてのフライト'}<strong>${s.level} · ${esc(s.theme)}</strong></div><span>セット ${s.number}</span></div></div><button class="primary mint wide continue" data-action="set" data-id="${s.id}"><span>${state.lastSet?'続きから学ぶ':'学習を始める'}<small>${esc(s.title)} · 習得 ${sc.mastered} / 20語</small></span><span class="arrow">→</span></button><div class="stats"><div><strong>${c.mastered}</strong><span>習得済み / ${ALL.length.toLocaleString()}語</span></div><div><strong>${state.flights}</strong><span>フライト回数</span></div><div><strong>${state.best}</strong><span>最高正解数</span></div></div>${progress(c.mastered,ALL.length)}<button class="secondary wide" data-action="review">間違えた単語を復習 <span class="badge">${c.review}語</span></button></section><section><h2>レベルから選ぶ</h2><div class="level-grid">${LEVELS.map((l,i)=>{const ss=SETS.filter(s=>s.level===l),ws=ss.flatMap(s=>s.words);return `<button class="level" data-action="level" data-id="${l}"><strong>${l}</strong><div>${['身近な基本語彙','毎日の暮らし','仕事・経験・意見','社会と抽象的な話題'][i]}</div><small>${ws.length}語 · ${ss.length}セット</small>${progress(counts(ws).mastered,ws.length)}</button>`;}).join('')}</div><div class="card section-gap"><h3>一緒に飛ぶキャラクター</h3><div class="avatar-list">${Object.entries(PILOTS).map(([k,[e,n]])=>`<button class="avatar ${state.pilot===k?'selected':''}" data-action="pilot" data-id="${k}" aria-pressed="${state.pilot===k}">${e}<span>${n}</span></button>`).join('')}</div><label class="audio-row"><input type="checkbox" id="audio" ${state.audio?'checked':''}>出題時に単語の音声を流す</label><p class="note">端末音声を使用します。声・北部発音への対応は端末により異なります。音声なしでも遊べます。</p></div></section></div>${footer()}</main>`;}
function levelView(){const ss=SETS.filter(s=>s.level===route.id),themes=[...new Set(ss.map(s=>s.theme))];return `<main class="shell">${crumbs({level:route.id})}<div class="eyebrow">CHOOSE A TOPIC</div><h1>${route.id} · テーマを選ぶ</h1><p class="muted">好きなテーマから始められます。</p><div class="theme-grid section-gap">${themes.map((t,i)=>{const ts=ss.filter(s=>s.theme===t),ws=ts.flatMap(s=>s.words),c=counts(ws);return `<button class="set-button" data-action="theme" data-level="${route.id}" data-id="${esc(t)}"><div class="row"><h3>${String(i+1).padStart(2,'0')}　${esc(t)}</h3><span>→</span></div><div class="caption">${ws.length}語 · ${ts.length}セット</div>${progress(c.mastered,ws.length)}<div class="caption">習得 ${c.mastered} / ${ws.length}語</div></button>`;}).join('')}</div></main>`;}
function themeView(){const ss=SETS.filter(s=>s.level===route.level&&s.theme===route.id);return `<main class="shell">${crumbs({level:route.level})}<div class="eyebrow">20 WORDS, ONE STEP</div><h1>${route.level} · ${esc(route.id)}</h1><p class="muted">20語ずつ、何度でも。2分で全部終わらなくても大丈夫。</p><div class="list section-gap">${ss.map(s=>{const c=counts(s.words);return `<button class="set-button" data-action="set" data-id="${s.id}"><div class="row"><div><h3>セット${s.number} · ${esc(s.title)}</h3><div class="caption">${c.seen===20?'全20語を回答済み':`未学習 ${20-c.seen}語`} · 苦手 ${c.review}語</div></div><span class="badge">習得 ${c.mastered} / 20</span></div>${progress(c.mastered,20)}</button>`;}).join('')}</div></main>`;}
function wordRows(words){return words.map(w=>{const x=status(w.id);return `<div class="word-row"><div><b lang="vi">${esc(w.vi)}</b><br><small>${x.streak>=3?'✓ 習得済み':x.review?'もう一度練習':x.seen?'学習中':'未学習'}</small></div><span>${esc(w.ja)}</span><button data-action="speak" data-id="${w.id}" aria-label="${esc(w.vi)}の発音を聞く">🔊</button></div>`;}).join('');}
function setView(){const s=bySet(route.id),c=counts(s.words);return `<main class="shell">${crumbs(s,true)}<div class="study-layout"><section><div class="eyebrow">SET ${String(s.number).padStart(2,'0')} · ${s.level}</div><h1>${esc(s.title)}</h1><p class="muted">${esc(s.theme)} · 20語</p><div class="sky section-gap"><span class="pilot idle" aria-hidden="true">${PILOTS[state.pilot][0]}</span><div class="sky-caption"><div>正解で上昇、間違えると下降。<strong>2分間、空を飛ぼう。</strong></div></div></div><div class="card section-gap"><div class="row"><span>習得済み</span><strong>${c.mastered} / 20語</strong></div>${progress(c.mastered,20)}<p class="caption">未学習 ${20-c.seen}語 · 苦手 ${c.review}語</p><div class="actions"><button class="primary mint" data-action="start" data-id="${s.id}">${c.seen&&c.seen<20?`残り${20-c.seen}語から続ける`:'ゲーム開始'} →</button><button class="secondary" data-action="start-review" data-id="${s.id}" ${c.review?'':'disabled'}>苦手${c.review}語をゲームで復習</button></div><p class="note">高度50から開始。正解＋8、不正解−18。回答中は毎秒1.2ずつ下降します。未回答は不正解になりません。</p></div></section><section class="card"><h2>単語を確認</h2><p class="caption">意味を予習してから、飛び立ちましょう。</p><div class="word-list">${wordRows(s.words)}</div><p class="note">1回の正解で習得済みにはなりません。別々のゲームで3回連続正解すると習得済みになります。</p></section></div></main>`;}
function reviewView(){const words=ALL.filter(w=>status(w.id).review);const sets=SETS.filter(s=>s.words.some(w=>status(w.id).review));return `<main class="shell"><nav class="breadcrumbs"><button data-action="home">ホーム</button><span>› 復習</span></nav><h1>間違えた単語を復習</h1><p class="muted">${words.length}語。未出題の単語は、各セットの「続き」から学べます。</p>${sets.length?`<div class="list section-gap">${sets.map(s=>`<section class="card"><div class="row"><h3>${s.level} · ${esc(s.title)}</h3><button class="secondary" data-action="start-review" data-id="${s.id}">復習する</button></div>${wordRows(s.words.filter(w=>status(w.id).review))}</section>`).join('')}</div>`:'<div class="card empty section-gap"><p>復習する単語はまだありません。</p><button class="primary" data-action="set" data-id="'+currentSet().id+'">学習へ進む</button></div>'}</main>`;}
function choicesFor(word,set){const used=new Set([word.ja]);const pool=[...shuffle(set.words),...shuffle(ALL.filter(w=>w.level===word.level))];const wrong=[];for(const w of pool){if(w.id!==word.id&&!(['canh','súp'].includes(word.id)&&['canh','súp'].includes(w.id))&&!used.has(w.ja)&&!w.ja.includes(word.ja)&&!word.ja.includes(w.ja)){used.add(w.ja);wrong.push(w.ja);if(wrong.length===3)break;}}return shuffle([word.ja,...wrong]);}
function queueFor(words){return [...shuffle(words.filter(w=>!status(w.id).seen)),...shuffle(words.filter(w=>status(w.id).seen&&status(w.id).review)),...shuffle(words.filter(w=>status(w.id).seen&&!status(w.id).review))];}
function start(id,reviewIds){const s=bySet(id),words=reviewIds?s.words.filter(w=>reviewIds.includes(w.id)):s.words;if(!words.length){toast('復習する単語はありません。');return;}cancelAnimationFrame(raf);stopVoice();state.lastSet=s.id;save();game={session:Date.now().toString(36)+Math.random().toString(36).slice(2),set:s,pool:words,queue:queueFor(words),altitude:50,elapsed:0,correct:0,wrong:0,combo:0,bestCombo:0,answered:new Set(),mistakes:new Set(),paused:false,finished:false,locked:false,feedbackLeft:0,review:!!reviewIds,lastTick:performance.now()};route={view:'game'};nextQuestion();render();updateHud();speak(game.word.vi);raf=requestAnimationFrame(tick);window.scrollTo(0,0);}
function nextQuestion(){if(!game.queue.length)game.queue=shuffle(game.pool);game.word=game.queue.shift();game.choices=choicesFor(game.word,game.set);game.locked=false;game.feedbackLeft=0;}
function gameView(){const g=game;return `<main class="game-shell"><div class="game-top"><span>${g.set.level} › ${esc(g.set.theme)} › セット${g.set.number}${g.review?' · 復習':''}</span><button class="secondary" data-action="pause">Ⅱ 一時停止</button></div><div class="game-hud"><div><small>残り時間</small><strong id="timer">2:00</strong></div><div><small>正解</small><strong id="correct">${g.correct}</strong></div><div><small>連続正解</small><strong id="combo">${g.combo}</strong></div></div><div class="sky game-sky"><span class="sky-label" style="left:auto;right:14px">${g.review?'REVIEW FLIGHT':'WORD FLIGHT'}</span><div class="altitude"><span id="alt-fill"></span></div><div class="altitude-number" id="alt-number">高度 50</div><span class="pilot" id="pilot" aria-hidden="true">${PILOTS[state.pilot][0]}</span><div class="distance"><span id="distance"></span></div><span class="goal" id="goal" aria-hidden="true">🏰</span></div><section class="quiz"><div class="question"><small>この単語の意味は？</small><h1 lang="vi" id="question">${esc(g.word.vi)}</h1></div><div class="choices" id="choices">${choiceButtons()}</div><div class="feedback" id="feedback" role="status" aria-live="polite"></div></section><div class="game-footer"><span id="answered">今回 ${g.answered.size} / ${g.pool.length}語に回答</span><span>正解 ＋8 / 不正解 −18</span></div></main>`;}
function choiceButtons(){return game.choices.map((c,i)=>`<button class="choice" data-action="answer" data-index="${i}"><span class="key">${i+1}</span><span>${esc(c)}</span></button>`).join('');}
function updateHud(){if(!game||route.view!=='game')return;const remaining=Math.max(0,Math.ceil(120-game.elapsed));document.getElementById('timer').textContent=`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`;document.getElementById('correct').textContent=game.correct;document.getElementById('combo').textContent=game.combo;document.getElementById('alt-number').textContent=`高度 ${Math.ceil(game.altitude)}`;document.getElementById('alt-fill').style.height=game.altitude+'%';document.getElementById('alt-fill').style.background=game.altitude<25?'#e17b57':'#199f85';document.getElementById('pilot').style.bottom=(4+game.altitude*.65)+'%';document.getElementById('distance').style.width=game.elapsed/120*100+'%';document.querySelector('.game-sky').style.backgroundPosition=(100-game.elapsed/120*100)+'% 76%';document.getElementById('answered').textContent=`今回 ${game.answered.size} / ${game.pool.length}語に回答`;}
function tick(now){const g=game;if(!g||g.finished)return;const dt=Math.max(0,(now-g.lastTick)/1000);g.lastTick=now;if(!g.paused){g.elapsed=Math.min(120,g.elapsed+dt);if(!g.locked)g.altitude=Math.max(0,g.altitude-dt*1.2);else{g.feedbackLeft-=dt;if(g.feedbackLeft<=0){nextQuestion();document.getElementById('question').textContent=g.word.vi;document.getElementById('choices').innerHTML=choiceButtons();document.getElementById('feedback').textContent='';speak(g.word.vi);}}updateHud();if(g.altitude<=0){finish('crash');return;}if(g.elapsed>=120){finish('clear');return;}}raf=requestAnimationFrame(tick);}
function answer(index){const g=game;if(!g||g.finished||g.paused||g.locked||!Number.isInteger(index)||index<0||index>3)return;const now=performance.now(),dt=Math.max(0,(now-g.lastTick)/1000);g.lastTick=now;g.elapsed=Math.min(120,g.elapsed+dt);g.altitude=Math.max(0,g.altitude-dt*1.2);if(g.altitude<=0){finish('crash');return;}if(g.elapsed>=120){finish('clear');return;}g.locked=true;g.feedbackLeft=.72;const ok=g.choices[index]===g.word.ja,x={...status(g.word.id)};x.seen++;g.answered.add(g.word.id);if(ok){g.correct++;g.combo++;g.bestCombo=Math.max(g.bestCombo,g.combo);g.altitude=Math.min(100,g.altitude+8);x.correct++;x.review=false;if(x.lastSession!==g.session){x.streak++;x.lastSession=g.session;}}else{g.wrong++;g.combo=0;g.altitude=Math.max(0,g.altitude-18);g.mistakes.add(g.word.id);x.wrong++;x.streak=0;x.review=true;x.lastSession=g.session;}state.words[g.word.id]=x;save();document.querySelectorAll('.choice').forEach((b,i)=>{b.disabled=true;if(g.choices[i]===g.word.ja)b.classList.add('correct');else if(i===index)b.classList.add('wrong');});document.getElementById('feedback').textContent=ok?'正解！ ＋8':`正解は「${g.word.ja}」 −18`;updateHud();if(g.altitude<=0){finish('crash');}}
function pause(){if(!game||game.finished||game.paused)return;game.paused=true;stopVoice();const d=document.createElement('div');d.className='overlay';d.id='pause-overlay';d.setAttribute('role','dialog');d.setAttribute('aria-modal','true');d.setAttribute('aria-label','一時停止');d.innerHTML='<section class="card"><div style="font-size:40px">Ⅱ</div><h2>ひと休み</h2><p class="muted">時間と高度は止まっています。</p><div class="actions"><button class="primary mint" data-action="resume">フライトを再開</button><button class="secondary" data-action="stop">ここまでの結果を見る</button></div></section>';app.append(d);d.querySelector('button').focus();}
function resume(){if(!game||game.finished)return;game.paused=false;game.lastTick=performance.now();document.getElementById('pause-overlay')?.remove();if(!game.locked)speak(game.word.vi);document.querySelector('[data-action="pause"]')?.focus();}
function finish(reason){if(!game||game.finished)return;game.finished=true;cancelAnimationFrame(raf);stopVoice();state.best=Math.max(state.best,game.correct);state.flights++;save();lastResult={...game,reason};const completed=game;const showResult=()=>{if(game!==completed)return;route={view:'result'};render();window.scrollTo(0,0);};if(reason==='stopped'){showResult();}else{updateHud();document.querySelector('.game-sky')?.classList.add(reason);document.querySelectorAll('.choice').forEach(b=>b.disabled=true);document.getElementById('feedback').textContent=reason==='clear'?'ゴールに到着！':'着地しました。学習結果を保存しています。';setTimeout(showResult,850);}}
function resultView(){const r=lastResult,s=r.set,c=counts(s.words),attempts=r.correct+r.wrong,remaining=20-c.seen,next=SETS[SETS.indexOf(s)+1];return `<main class="shell" style="max-width:760px"><div class="result-title"><div class="emoji">${r.reason==='clear'?'🏰':r.reason==='crash'?'🪂':'☕'}</div><div class="eyebrow">${r.reason==='clear'?'FLIGHT COMPLETE':r.reason==='crash'?'TRY ANOTHER FLIGHT':'FLIGHT SAVED'}</div><h1>${r.reason==='clear'?'ゴールに到着！':r.reason==='crash'?'着地。もう一度、飛ぼう。':'ここまでの学習を保存しました。'}</h1><p class="muted">${s.level} · ${esc(s.theme)} · セット${s.number}</p></div><section class="card"><div class="result-grid"><div class="result-stat"><strong>${r.correct}</strong><span>正解数</span></div><div class="result-stat"><strong>${r.wrong}</strong><span>不正解数</span></div><div class="result-stat"><strong>${attempts?Math.round(r.correct/attempts*100):0}<small>%</small></strong><span>正答率</span></div></div><div class="summary-table"><div class="row"><span>最大連続正解</span><strong>${r.bestCombo}問</strong></div><div class="row"><span>今回回答した単語</span><strong>${r.answered.size} / ${r.pool.length}語</strong></div><div class="row"><span>このセットの未学習</span><strong>${remaining}語</strong></div><div class="row"><span>このセットの習得済み</span><strong>${c.mastered} / 20語</strong></div></div><p class="note">未出題・未回答の単語は不正解にせず、次のゲームに残しています。</p><div class="actions"><button class="primary mint" data-action="start" data-id="${s.id}">${remaining?`残り${remaining}語から続ける`:'この20語をもう一度練習'} →</button>${r.mistakes.size?`<button class="secondary" data-action="result-review">今回間違えた${r.mistakes.size}語を復習</button>`:''}${!remaining&&next?`<button class="secondary" data-action="set" data-id="${next.id}">次のセットへ · ${next.level} ${esc(next.title)}</button>`:''}<button class="plain" data-action="set" data-id="${s.id}">単語一覧へ戻る</button><button class="plain" data-action="home">ホームへ</button></div></section>${r.mistakes.size?`<section class="card section-gap"><h2>今回間違えた単語</h2>${wordRows([...r.mistakes].map(id=>BY_ID.get(id)))}</section>`:''}</main>`;}
function stopVoice(){try{window.speechSynthesis?.cancel();}catch{}}
function speak(text,force=false){if(!state.audio&&!force)return;const synth=window.speechSynthesis;if(!synth){if(force)toast('この端末では音声を利用できません。');return;}const voices=synth.getVoices().filter(v=>/^vi([_-]|$)/i.test(v.lang));if(!voices.length){if(force)toast('ベトナム語の端末音声が見つかりません。音声なしで学習できます。');return;}const voice=voices.find(v=>/HoaiMy|NamMinh/i.test(v.name))||voices[0];synth.cancel();const u=new SpeechSynthesisUtterance(text);u.voice=voice;u.lang=voice.lang;u.rate=.9;u.onerror=()=>{};synth.speak(u);}
app.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,id=b.dataset.id;if(a==='home')go('home');else if(a==='level')go('level',{id});else if(a==='theme')go('theme',{id,level:b.dataset.level});else if(a==='set'){state.lastSet=bySet(id).id;save();go('set',{id});}else if(a==='pilot'){state.pilot=id;save();render();}else if(a==='review')go('review');else if(a==='speak')speak(BY_ID.get(id).vi,true);else if(a==='start')start(id);else if(a==='start-review')start(id,bySet(id).words.filter(w=>status(w.id).review).map(w=>w.id));else if(a==='result-review')start(lastResult.set.id,[...lastResult.mistakes]);else if(a==='answer')answer(Number(b.dataset.index));else if(a==='pause')pause();else if(a==='resume')resume();else if(a==='stop')finish('stopped');});
app.addEventListener('change',e=>{if(e.target.id==='audio'){state.audio=e.target.checked;save();if(state.audio)speak('xin chào',true);else stopVoice();}});
window.addEventListener('keydown',e=>{if(game&&!game.finished){if(e.key==='Escape'){e.preventDefault();game.paused?resume():pause();}else if(/^[1-4]$/.test(e.key)&&!e.repeat){e.preventDefault();answer(Number(e.key)-1);}else if(e.key==='Tab'&&game.paused){const bs=[...document.querySelectorAll('#pause-overlay button')],i=bs.indexOf(document.activeElement);e.preventDefault();bs[(i+(e.shiftKey?-1:1)+bs.length)%bs.length].focus();}}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
window.addEventListener('pagehide',()=>{stopVoice();save();});
render();
if(document.modelContext?.registerTool){try{const lifetime=new AbortController();window.addEventListener('pagehide',()=>lifetime.abort(),{once:true});for(const tool of [{name:'read_learning_progress',description:'現在の端末に保存された学習進捗を読み取ります。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({total:ALL.length,...counts(ALL),lastSet:state.lastSet,flights:state.flights})},{name:'open_vocabulary_set',description:'指定した20語のセット画面を開きます。ゲームは開始しません。',inputSchema:{type:'object',properties:{setId:{type:'string'}},required:['setId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||typeof input.setId!=='string'||!SETS.some(s=>s.id===input.setId))throw new Error('Unknown setId');if(game&&!game.finished)throw new Error('Finish or stop the current flight first');state.lastSet=input.setId;save();go('set',{id:input.setId});return {setId:input.setId,view:'set'};}}])Promise.resolve(document.modelContext.registerTool(tool,{signal:lifetime.signal})).catch(()=>{});}catch{}}


